import type { Employee, LeaveRequest } from './types'

export const employees: Employee[] = [
  {
    id: 'emp-1',
    firstName: 'Camille',
    lastName: 'Durand',
    department: 'Ingénierie',
    role: 'Développeuse Frontend',
    color: '#6366f1',
    balancePaid: 14,
    balanceRtt: 3,
  },
  {
    id: 'emp-2',
    firstName: 'Lucas',
    lastName: 'Moreau',
    department: 'Ingénierie',
    role: 'Développeur Backend',
    color: '#0ea5e9',
    balancePaid: 9,
    balanceRtt: 5,
  },
  {
    id: 'emp-3',
    firstName: 'Inès',
    lastName: 'Cavalcanti',
    department: 'Produit',
    role: 'Product Manager',
    color: '#ec4899',
    balancePaid: 21,
    balanceRtt: 2,
  },
  {
    id: 'emp-4',
    firstName: 'Nathan',
    lastName: 'Petit',
    department: 'Ventes',
    role: 'Responsable Commercial',
    color: '#f59e0b',
    balancePaid: 6,
    balanceRtt: 0,
  },
  {
    id: 'emp-5',
    firstName: 'Sarah',
    lastName: 'Bernard',
    department: 'RH',
    role: 'Chargée de recrutement',
    color: '#10b981',
    balancePaid: 18,
    balanceRtt: 4,
  },
  {
    id: 'emp-6',
    firstName: 'Yanis',
    lastName: 'Lefèvre',
    department: 'Ingénierie',
    role: 'DevOps',
    color: '#8b5cf6',
    balancePaid: 11,
    balanceRtt: 6,
  },
]

export const leaveRequests: LeaveRequest[] = [
  {
    id: 'req-1',
    employeeId: 'emp-1',
    type: 'Congés payés',
    startDate: '2026-09-07',
    endDate: '2026-09-11',
    days: 5,
    status: 'En attente',
    reason: 'Vacances en famille',
    createdAt: '2026-08-20',
  },
  {
    id: 'req-2',
    employeeId: 'emp-2',
    type: 'RTT',
    startDate: '2026-09-01',
    endDate: '2026-09-01',
    days: 1,
    status: 'Approuvé',
    reason: 'Rendez-vous personnel',
    createdAt: '2026-08-18',
  },
  {
    id: 'req-3',
    employeeId: 'emp-3',
    type: 'Congés payés',
    startDate: '2026-10-05',
    endDate: '2026-10-16',
    days: 10,
    status: 'En attente',
    reason: "Voyage à l'étranger",
    createdAt: '2026-08-25',
  },
  {
    id: 'req-4',
    employeeId: 'emp-4',
    type: 'Maladie',
    startDate: '2026-08-18',
    endDate: '2026-08-19',
    days: 2,
    status: 'Approuvé',
    reason: 'Arrêt maladie',
    createdAt: '2026-08-18',
  },
  {
    id: 'req-5',
    employeeId: 'emp-5',
    type: 'Événement familial',
    startDate: '2026-09-14',
    endDate: '2026-09-14',
    days: 1,
    status: 'Refusé',
    reason: 'Mariage',
    createdAt: '2026-08-15',
  },
  {
    id: 'req-6',
    employeeId: 'emp-6',
    type: 'Sans solde',
    startDate: '2026-11-02',
    endDate: '2026-11-06',
    days: 5,
    status: 'En attente',
    reason: 'Projet personnel',
    createdAt: '2026-08-28',
  },
  {
    id: 'req-7',
    employeeId: 'emp-1',
    type: 'RTT',
    startDate: '2026-08-24',
    endDate: '2026-08-24',
    days: 1,
    status: 'Approuvé',
    reason: 'Pont du 15 août',
    createdAt: '2026-08-10',
  },
]
